blanguage: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
cache: cargo

notifications:
  email:
    recipients: paho@paholg.com

# fixme: re-enable rustfmt when it works
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - export TRAVIS_CARGO_NIGHTLY_FEATURE=""
  # - test -x $HOME/.cargo/bin/rustfmt || cargo install rustfmt # Only install rustfmt if it's not there

script:
    # PATH=$PATH:~/.cargo/bin cargo fmt -- --write-mode=diff &&
  - |
    travis-cargo --only stable test &&
    travis-cargo --only beta test &&
    travis-cargo --only nightly test -- --features "oibit qc clippy" &&
    travis-cargo --only stable doc

after_success:
  - travis-cargo doc-upload
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && cargo publish --token ${CRATESIO_TOKEN}

env:
  global:
  - secure: ZKVATaNNGsoAdISoshGxDt82Ie4lgbrn91cRK+hjQvtAJjlWva554l49P5RU6T4ZkGFC2PyQ/zF8jMmNsPJUeQ3F2E4v1NVw83CrSoqIRmtDzN6kgblshPAZVX8xNsEZarEV+dw+CTA7a5c0J0Nm38lIaxwuntvO47x8Zf0RFZc=
  - secure: YOsYYXcwIx8UZgcI4pPMi6sH6QLYGWpkogQLO53yQYzzpshw1XeKI+QD2Zx5zpUtocyP37zWJwvZZLEcs9auy4W2lrsFrwz0yB3PfzqOo9vDsxcAfm8Ycb+Uvvplwd6DUmRwqAp7XJqzbcL1K0MNezY9+bmE78JVG3WeGn2GGO0=
